apiVersion: v1
kind: Service

metadata:
  name: backend
  namespace: fincompliance

spec:
  selector:
    app: backend

  ports:
    - name: http
      port: 8000
      targetPort: 8000

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: fincompliance

spec:
  replicas: 2

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: backend

          image: fincompliance/backend:phase12

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: fincompliance-config

            - secretRef:
                name: fincompliance-secrets

          env:
            - name: EVENT_SERVICE_URL
              value: "http://event-service:3001"

            - name: CHROMA_HOST
              value: "chroma"

            - name: CHROMA_PORT
              value: "8000"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 8
            periodSeconds: 5

            timeoutSeconds: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 25
            periodSeconds: 10

            timeoutSeconds: 5

          resources:
            requests:
              cpu: "150m"
              memory: "192Mi"

            limits:
              cpu: "1"
              memory: "1Gi"

---

apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
  name: backend-pdb
  namespace: fincompliance

spec:
  minAvailable: 1

  selector:
    matchLabels:
      app: backend
