apiVersion: v1
kind: Secret

metadata:
  name: fincompliance-secrets
  namespace: fincompliance

type: Opaque

stringData:
  POSTGRES_USER: replace-me
  POSTGRES_PASSWORD: replace-me
  POSTGRES_DB: fincompliance

  DATABASE_URL: replace-me

  MONGO_URL: mongodb://mongo:27017

  RABBITMQ_USER: replace-me
  RABBITMQ_PASSWORD: replace-me
  RABBITMQ_URL: replace-me

  JWT_SECRET: replace-me

  AUTH_VIEWER_USERNAME: viewer
  AUTH_VIEWER_PASSWORD_SALT: replace-me
  AUTH_VIEWER_PASSWORD_HASH: replace-me

  AUTH_ANALYST_USERNAME: analyst
  AUTH_ANALYST_PASSWORD_SALT: replace-me
  AUTH_ANALYST_PASSWORD_HASH: replace-me

  AUTH_ADMIN_USERNAME: admin
  AUTH_ADMIN_PASSWORD_SALT: replace-me
  AUTH_ADMIN_PASSWORD_HASH: replace-me
